services:
  infra-monitor:
    build: .
    container_name: infra-monitor
    ports:
      - "8000:8000"

    # Load environment variables from local .env file
    env_file:
      - .env

    # FÃ¼r Entwicklung mit Live-Reload (optional):
    volumes:
      - ./app:/app/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

